[application]
name = "lulu-logs"
default_platform = "desktop"

[web.app]
title = "lulu-logs"

[web.watcher]

[web.resource]
style = ["assets/style.css"]

[web.resource.dev]

[desktop]

[bundle]
identifier = "com.xdoctorwhoz"
publisher = "XdoctorwhoZ"