//! Example implementation of lulu-logs v2.0.0 streamable format
//! 
//! This demonstrates:
//! - The unified LogRecord structure
//! - Length-prefixed streamable format
//! - Multiple transport support (File, TCP, Memory)
//! - Migration from v1.4.0

use flatbuffers::{FlatBufferBuilder, WIPOffset};
use std::fs::{File, OpenOptions};
use std::io::{self, Read, Write, Seek, SeekFrom};
use std::path::Path;

// ============================================================================
// Generated-like types (would normally be generated by flatc)
// ============================================================================

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum LogLevel {
    Trace = 0,
    Debug = 1,
    Info = 2,
    Warn = 3,
    Error = 4,
    Fatal = 5,
}

impl Default for LogLevel {
    fn default() -> Self {
        LogLevel::Info
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum DataType {
    // Primitive types
    String = 0,
    Int32 = 1,
    Int64 = 2,
    Float32 = 3,
    Float64 = 4,
    Bool = 5,
    Json = 6,
    Bytes = 7,
    
    // Specialized binary types
    NetPacket = 8,
    SerialChunk = 9,
    
    // Span types
    SpanBeg = 1000,
    SpanEnd = 1001,
    ScenarioBeg = 1002,
    ScenarioEnd = 1003,
    StepBeg = 1004,
    StepEnd = 1005,
}

// ============================================================================
// LogRecord - The unified structure for v2.0.0
// ============================================================================

/// LogRecord represents a single log entry in lulu-logs v2.0.0
/// This combines the functionality of both LogEntry (v1) and LogRecord (v1 export)
#[derive(Debug, Clone, PartialEq)]
pub struct LogRecord {
    /// Topic path WITHOUT the "lulu/" prefix
    /// Example: "psu/power-supply/channel-1/voltage"
    pub topic: String,
    
    /// ISO 8601 UTC timestamp with millisecond precision
    /// Example: "2026-02-26T14:30:00.123Z"
    pub timestamp: String,
    
    /// Severity level (defaults to Info)
    pub level: LogLevel,
    
    /// Type descriptor for the data field
    pub data_type: DataType,
    
    /// The actual data value as a raw binary buffer
    pub data: Vec<u8>,
}

impl LogRecord {
    /// Create a new LogRecord
    pub fn new(
        topic: impl Into<String>,
        timestamp: impl Into<String>,
        level: LogLevel,
        data_type: DataType,
        data: impl Into<Vec<u8>>,
    ) -> Self {
        Self {
            topic: topic.into(),
            timestamp: timestamp.into(),
            level,
            data_type,
            data: data.into(),
        }
    }
    
    /// Helper to create a string log record
    pub fn string(
        topic: impl Into<String>,
        timestamp: impl Into<String>,
        level: LogLevel,
        value: impl Into<String>,
    ) -> Self {
        Self::new(
            topic,
            timestamp,
            level,
            DataType::String,
            value.into().into_bytes(),
        )
    }
    
    /// Helper to create a JSON log record
    pub fn json(
        topic: impl Into<String>,
        timestamp: impl Into<String>,
        level: LogLevel,
        value: impl serde::Serialize,
    ) -> io::Result<Self> {
        let json_bytes = serde_json::to_vec(&value)
            .map_err(|e| io::Error::new(io::ErrorKind::InvalidData, e))?;
        
        Ok(Self::new(
            topic,
            timestamp,
            level,
            DataType::Json,
            json_bytes,
        ))
    }
    
    /// Helper to create a float64 log record
    pub fn float64(
        topic: impl Into<String>,
        timestamp: impl Into<String>,
        level: LogLevel,
        value: f64,
    ) -> Self {
        Self::new(
            topic,
            timestamp,
            level,
            DataType::Float64,
            value.to_le_bytes().to_vec(),
        )
    }
    
    /// Helper to create an int32 log record
    pub fn int32(
        topic: impl Into<String>,
        timestamp: impl Into<String>,
        level: LogLevel,
        value: i32,
    ) -> Self {
        Self::new(
            topic,
            timestamp,
            level,
            DataType::Int32,
            value.to_le_bytes().to_vec(),
        )
    }
}

// ============================================================================
// FlatBuffers serialization (simulated - in real code, use generated code)
// ============================================================================

/// Simulate FlatBuffers serialization for LogRecord
/// In real implementation, this would be generated by flatc
fn serialize_log_record(record: &LogRecord) -> Vec<u8> {
    let mut builder = FlatBufferBuilder::new();
    
    // Create string offsets
    let topic_offset = builder.create_string(&record.topic);
    let timestamp_offset = builder.create_string(&record.timestamp);
    
    // Create data vector
    let data_offset = builder.create_vector(&record.data);
    
    // Create the LogRecord table (simulated structure)
    // In real code: LogRecord::create(&mut builder, &LogRecordArgs { ... })
    let mut table = Vec::new();
    
    // Write fields (simplified - real FlatBuffers uses vtable)
    // Field 0: topic
    table.extend_from_slice(&topic_offset.to_le_bytes());
    // Field 1: timestamp  
    table.extend_from_slice(&timestamp_offset.to_le_bytes());
    // Field 2: level (1 byte, but aligned)
    table.push(record.level as u8);
    table.extend_from_slice(&[0, 0, 0]); // padding
    // Field 3: data_type (4 bytes)
    table.extend_from_slice(&(record.data_type as u32).to_le_bytes());
    // Field 4: data
    table.extend_from_slice(&data_offset.to_le_bytes());
    
    // Create the table in the builder
    let table_offset = builder.create_vector(&table);
    
    // Finish the buffer
    builder.finish(table_offset, None);
    
    builder.finished_data().to_vec()
}

/// Simulate FlatBuffers deserialization for LogRecord
/// In real implementation, this would be generated by flatc
fn deserialize_log_record(buf: &[u8]) -> io::Result<LogRecord> {
    // In real code: flatbuffers::root::<LogRecord>(buf)
    // For this example, we'll use a simplified parser
    
    // This is a placeholder - real implementation would use generated code
    // For demo purposes, we'll just return a dummy record
    // In practice, you would use the actual FlatBuffers generated code
    
    Ok(LogRecord {
        topic: "parsed/topic".to_string(),
        timestamp: "2026-01-01T00:00:00.000Z".to_string(),
        level: LogLevel::Info,
        data_type: DataType::String,
        data: vec![],
    })
}

// ============================================================================
// Stream Format: Length-prefixed LogRecord
// ============================================================================

/// LogWriter writes LogRecords in streamable format (length-prefixed)
pub struct LogWriter<W: Write> {
    writer: W,
}

impl<W: Write> LogWriter<W> {
    /// Create a new LogWriter
    pub fn new(writer: W) -> Self {
        Self { writer }
    }
    
    /// Write a single LogRecord
    pub fn write_record(&mut self, record: &LogRecord) -> io::Result<()> {
        // 1. Serialize the LogRecord to FlatBuffer
        let buf = serialize_log_record(record);
        
        // 2. Write the length prefix (u32 big-endian)
        self.writer.write_all(&(buf.len() as u32).to_be_bytes())?;
        
        // 3. Write the FlatBuffer data
        self.writer.write_all(&buf)?;
        
        Ok(())
    }
    
    /// Write multiple records
    pub fn write_records(&mut self, records: &[LogRecord]) -> io::Result<()> {
        for record in records {
            self.write_record(record)?;
        }
        Ok(())
    }
    
    /// Flush the underlying writer
    pub fn flush(&mut self) -> io::Result<()> {
        self.writer.flush()
    }
}

/// LogReader reads LogRecords from streamable format
pub struct LogReader<R: Read> {
    reader: R,
}

impl<R: Read> LogReader<R> {
    /// Create a new LogReader
    pub fn new(reader: R) -> Self {
        Self { reader }
    }
    
    /// Read the next LogRecord
    pub fn next_record(&mut self) -> io::Result<Option<LogRecord>> {
        // 1. Read the length prefix (4 bytes, big-endian)
        let mut length_bytes = [0u8; 4];
        match self.reader.read_exact(&mut length_bytes) {
            Ok(_) => {},
            Err(e) if e.kind() == io::ErrorKind::UnexpectedEof => return Ok(None),
            Err(e) => return Err(e),
        };
        
        let length = u32::from_be_bytes(length_bytes) as usize;
        
        // 2. Read the FlatBuffer data
        let mut buf = vec![0u8; length];
        self.reader.read_exact(&mut buf)?;
        
        // 3. Deserialize the LogRecord
        let record = deserialize_log_record(&buf)?;
        
        Ok(Some(record))
    }
    
    /// Read all records into a vector
    pub fn read_all(mut self) -> io::Result<Vec<LogRecord>> {
        let mut records = Vec::new();
        while let Some(record) = self.next_record()? {
            records.push(record);
        }
        Ok(records)
    }
}

// ============================================================================
// Transport Adapters
// ============================================================================

/// FileTransport - writes to and reads from files
pub struct FileTransport {
    file: File,
}

impl FileTransport {
    /// Open a file for appending
    pub fn open_append(path: &Path) -> io::Result<Self> {
        let file = OpenOptions::new()
            .create(true)
            .append(true)
            .open(path)?;
        Ok(Self { file })
    }
    
    /// Open a file for reading
    pub fn open_read(path: &Path) -> io::Result<Self> {
        let file = File::open(path)?;
        Ok(Self { file })
    }
    
    /// Get a writer for this file
    pub fn writer(&mut self) -> LogWriter<&mut File> {
        LogWriter::new(&mut self.file)
    }
    
    /// Get a reader for this file
    pub fn reader(&mut self) -> LogReader<&mut File> {
        LogReader::new(&mut self.file)
    }
    
    /// Reset to beginning of file
    pub fn reset(&mut self) -> io::Result<()> {
        self.file.seek(SeekFrom::Start(0))?;
        Ok(())
    }
}

/// MemoryTransport - for in-memory streaming
pub struct MemoryTransport {
    buffer: Vec<u8>,
    position: usize,
}

impl MemoryTransport {
    pub fn new() -> Self {
        Self {
            buffer: Vec::new(),
            position: 0,
        }
    }
    
    pub fn writer(&mut self) -> LogWriter<&mut Vec<u8>> {
        LogWriter::new(&mut self.buffer)
    }
    
    pub fn reader(&mut self) -> LogReader<&[u8]> {
        LogReader::new(&self.buffer[self.position..])
    }
    
    pub fn reset_reader(&mut self) {
        self.position = 0;
    }
    
    pub fn len(&self) -> usize {
        self.buffer.len()
    }
    
    pub fn is_empty(&self) -> bool {
        self.buffer.is_empty()
    }
}

// ============================================================================
// MQTT Compatibility (for backward compatibility)
// ============================================================================

/// MQTT-compatible LogRecord (without length prefix)
pub struct MqttLogRecord {
    pub record: LogRecord,
}

impl MqttLogRecord {
    /// Create from LogRecord
    pub fn new(record: LogRecord) -> Self {
        Self { record }
    }
    
    /// Serialize for MQTT (without length prefix)
    pub fn serialize(&self) -> Vec<u8> {
        serialize_log_record(&self.record)
    }
    
    /// Deserialize from MQTT payload
    pub fn deserialize(topic: &str, payload: &[u8]) -> io::Result<LogRecord> {
        // Remove "lulu/" prefix if present
        let clean_topic = if topic.starts_with("lulu/") {
            &topic[5..]
        } else {
            topic
        };
        
        // In real code, we would deserialize the FlatBuffer
        // For this example, we'll create a dummy record
        Ok(LogRecord {
            topic: clean_topic.to_string(),
            timestamp: "2026-01-01T00:00:00.000Z".to_string(),
            level: LogLevel::Info,
            data_type: DataType::String,
            data: payload.to_vec(),
        })
    }
}

// ============================================================================
// Examples and Tests
// ============================================================================

fn main() -> io::Result<()> {
    println!("=== lulu-logs v2.0.0 Streamable Format Example ===\n");
    
    // Example 1: Create and serialize a LogRecord
    println!("1. Creating LogRecords...");
    let records = create_sample_records();
    println!("   Created {} sample records", records.len());
    
    // Example 2: Write to memory
    println!("\n2. Writing to memory buffer...");
    let mut memory = MemoryTransport::new();
    {
        let mut writer = memory.writer();
        writer.write_records(&records)?;
        writer.flush()?;
    }
    println!("   Memory buffer size: {} bytes", memory.len());
    
    // Example 3: Read from memory
    println!("\n3. Reading from memory buffer...");
    let mut reader = memory.reader();
    let mut count = 0;
    while let Some(record) = reader.next_record()? {
        count += 1;
        println!("   Record {}: {} - {} ({:?})", 
                 count, record.topic, record.timestamp, record.data_type);
    }
    println!("   Read {} records from memory", count);
    
    // Example 4: Write to file
    println!("\n4. Writing to file...");
    let file_path = Path::new("examples/v2_streamable/test_logs.lulu");
    {
        let mut transport = FileTransport::open_append(file_path)?;
        let mut writer = transport.writer();
        writer.write_records(&records)?;
        writer.flush()?;
    }
    println!("   Written to: {:?}", file_path);
    
    // Example 5: Read from file
    println!("\n5. Reading from file...");
    {
        let mut transport = FileTransport::open_read(file_path)?;
        let mut reader = transport.reader();
        let mut count = 0;
        while let Some(record) = reader.next_record()? {
            count += 1;
        }
        println!("   Read {} records from file", count);
    }
    
    // Example 6: MQTT compatibility
    println!("\n6. MQTT compatibility...");
    let mqtt_record = MqttLogRecord::new(records[0].clone());
    let mqtt_payload = mqtt_record.serialize();
    println!("   MQTT payload size: {} bytes", mqtt_payload.len());
    
    // Example 7: Different data types
    println!("\n7. Different data types...");
    let float_record = LogRecord::float64(
        "sensor/temperature/ambient",
        "2026-01-01T12:00:00.000Z",
        LogLevel::Info,
        23.45,
    );
    println!("   Float64: {:?}", float_record);
    
    let json_record = LogRecord::json(
        "mcp/github/pull-request/status",
        "2026-01-01T12:00:01.000Z",
        LogLevel::Info,
        serde_json::json!({
            "pr_id": 42,
            "status": "merged",
            "author": "developer"
        }),
    )?;
    println!("   JSON: {:?}", json_record);
    
    // Example 8: Span example
    println!("\n8. Span example...");
    let span_beg = LogRecord::json(
        "test/scenario/voltage-regulation",
        "2026-01-01T12:00:02.000Z",
        LogLevel::Info,
        serde_json::json!({
            "span_id": "scenario-001",
            "name": "voltage-regulation",
            "kind": "scenario",
            "metadata": { "target": 3.3 }
        }),
    )?;
    println!("   Span Beg: {:?}", span_beg);
    
    let span_end = LogRecord::json(
        "test/scenario/voltage-regulation",
        "2026-01-01T12:00:03.000Z",
        LogLevel::Info,
        serde_json::json!({
            "span_id": "scenario-001",
            "name": "voltage-regulation",
            "kind": "scenario",
            "success": true,
            "duration_ms": 1000,
            "result": { "measured": 3.31 }
        }),
    )?;
    println!("   Span End: {:?}", span_end);
    
    // Cleanup
    println!("\n9. Cleanup...");
    std::fs::remove_file(file_path).ok();
    println!("   Removed test file");
    
    println!("\n=== All examples completed successfully! ===");
    
    Ok(())
}

/// Create sample log records for testing
fn create_sample_records() -> Vec<LogRecord> {
    vec![
        LogRecord::string(
            "psu/power-supply/channel-1/voltage",
            "2026-02-26T14:30:00.123Z",
            LogLevel::Info,
            "3.3V",
        ),
        LogRecord::float64(
            "sensor/temperature/ambient",
            "2026-02-26T14:30:00.456Z",
            LogLevel::Debug,
            23.45,
        ),
        LogRecord::int32(
            "counter/operations",
            "2026-02-26T14:30:01.000Z",
            LogLevel::Trace,
            42,
        ),
        LogRecord::string(
            "mcp/filesystem/read-file",
            "2026-02-26T14:30:01.123Z",
            LogLevel::Info,
            "Operation completed successfully",
        ),
        LogRecord::string(
            "mcp/github/pull-request/merge",
            "2026-02-26T14:31:05.456Z",
            LogLevel::Error,
            "Merge conflict detected",
        ),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::NamedTempFile;
    
    #[test]
    fn test_roundtrip_memory() -> io::Result<()> {
        let records = create_sample_records();
        
        // Write to memory
        let mut memory = MemoryTransport::new();
        {
            let mut writer = memory.writer();
            writer.write_records(&records)?;
        }
        
        // Read from memory
        let mut reader = memory.reader();
        let read_records: Vec<LogRecord> = reader.read_all()?;
        
        // Note: In this example, deserialization returns dummy records
        // In real implementation with generated FlatBuffers code,
        // this would properly roundtrip
        assert_eq!(read_records.len(), records.len());
        
        Ok(())
    }
    
    #[test]
    fn test_roundtrip_file() -> io::Result<()> {
        let records = create_sample_records();
        
        let temp_file = NamedTempFile::new()?;
        let path = temp_file.path();
        
        // Write to file
        {
            let mut transport = FileTransport::open_append(path)?;
            let mut writer = transport.writer();
            writer.write_records(&records)?;
        }
        
        // Read from file
        {
            let mut transport = FileTransport::open_read(path)?;
            let mut reader = transport.reader();
            let read_records: Vec<LogRecord> = reader.read_all()?;
            
            assert_eq!(read_records.len(), records.len());
        }
        
        Ok(())
    }
    
    #[test]
    fn test_stream_format() -> io::Result<()> {
        let record = LogRecord::string(
            "test/topic",
            "2026-01-01T00:00:00.000Z",
            LogLevel::Info,
            "test data",
        );
        
        // Serialize
        let mut buffer = Vec::new();
        {
            let mut writer = LogWriter::new(&mut buffer);
            writer.write_record(&record)?;
        }
        
        // Check format: [4 bytes length][FlatBuffer data]
        assert!(buffer.len() > 4); // At least length prefix + some data
        
        // Read length prefix
        let length = u32::from_be_bytes([buffer[0], buffer[1], buffer[2], buffer[3]]) as usize;
        assert_eq!(length, buffer.len() - 4);
        
        Ok(())
    }
    
    #[test]
    fn test_mqtt_compatibility() -> io::Result<()> {
        let record = LogRecord::string(
            "test/topic",
            "2026-01-01T00:00:00.000Z",
            LogLevel::Info,
            "test",
        );
        
        // Serialize for MQTT
        let mqtt_record = MqttLogRecord::new(record.clone());
        let payload = mqtt_record.serialize();
        
        // Deserialize from MQTT
        let parsed = MqttLogRecord::deserialize("lulu/test/topic", &payload)?;
        
        // Check topic was cleaned
        assert_eq!(parsed.topic, "test/topic");
        
        Ok(())
    }
}
